package com.aislingstuffthatmatters.personal_can_care;

import android.os.Build;

import androidx.annotation.RequiresApi;

import java.util.concurrent.ThreadLocalRandom;

public class QuoteServ {

    String[] getQuote(){

        //change String[] quotes = new String[]{ to
        return new String[]{
                "You are strong enough to fight through this!",
                "Your life is YOUR story,\n Write Well, Edit Often.",
                "We don't know how strong we are, until being strong is the only choice we have!!",
                "Always remember, You are BRAVER than you know, STRONGER than you seem and LOVED more than you know.",
                "Cancer didn't bring me to my knees, it brought me to my feet.",
                "The human spirit is stronger than anything that can happen to it.",
                "Always remember, you are Braver than you believe,\nStronger than you seen,\nSmarter than you think and\nTwice as Beautiful as you would ever imagine.",
                "Never be ashamed of a scar.\nIt simply means that you are stronger than whatever tried to hurt you.",
                "Never give up, never give in.",
                "Cancer is only going to be a chapter in your live's book, NOT the whole story.",
                "Cancer may have started the fight, but I will finish it.",
                "Believing you can and you are halfway there.",
                "Keep putting one foot in front of the other.\nThat's all you need to do right now.",
                "I have loved the stars too fondly, to be fearful of the night!!",
                "Don't let cancer define you. \nBe the warrior you were always meant to be.",
                "October is breast cancer awareness month.\nBut for a survivor, it is every single day.",
                "There is a 'can' in cancer because\n we CAN beat it.",
                "Only in the darkness can you see the stars.",
                "Please do not try to save me.\nStand by my side while I save myself.",
                "You get cancer, cancer DOES NOT get you.",
                "You are allowed to scream and cry.\nBut please do not give up.",
                "Your illness does not define you.\nYour strength and courage do.",
                "Don't look back, you are not going that way.",
                "HOPE \n*** \nHold On, Pain Ends.",
                "If you want the rainbow, you have got to put up with the rain.",
                "Fighter \n***\n Survivor \n***\n WARRIOR",
                "Never give up.",
                "There can be life after cancer.",
                "We could have cancer but cancer should never have us.",
                "Sometimes you have to go through things, not around them.",
                "Turn your face towards the sun and the shadows fall behind you.",
                "Just keep putting one foot in front of the other. \nThat's all you need to do right now.",
                "Do something today that your future self will thank you for.",
                "Strength doesn't come from what you can do. \nIt comes from overcoming the things \nyou once thought you couldn't do.",
                "Your mind is a powerful thing.  \nWhen you fill it with positive thoughts, \nyour life will start to change.",
                "Stay positive.",
                "Stay Strong.",
                "It's alright to cry.",
                "To all the fighters out there \n***\nYou got this.",
                "Find your joy.",
                "Laugh heartily.",
                "Reach out, there is support.",
                "You are not alone.",
                "Believe.",
                "See a sunrise.",
                "Watch a sunset.",
                "Celebrate life.",
                "Laugh.",
                "Have a little faith.",
                "Smile often.",
                "Listen to the rain.",
                "Explore the unknown.",
                "Have HOPE",
                "Slow Down",
                "Strength is looking back and seeing what you've been through and knowing you were strong enough to make it through.",
                "Small steps, every day.",
                "You are special",
                "You are AWESOME",
                "You are tough",
                "You are loved",
                "you are supported",
                "You are worth it",
                "You are amazing",
                "You are a fighter",
                "You are a survivor",
                "You are brave",
                "You are courageous",
                "Roads were made for journeys, \nnot destinations.",
                "Every day may not be good, \nbut there's good in every day.",
                "You were given this life because you are strong enough to live it.",
                "Not all of us can do great things, \nbut we can do small things with great love.",
                "Be strong, you never know who you are inspiring.",
                "It's not the years in your life that count. \nIt's the life in your years.",
                "You are not alone.",
                "Remember, it is how far you have come, not just how far you have got to go.",
                "You may not be where you want to be, but neither are you where you used to be.",
                "Be thankful for this day.  You are here, breathing and living life.",
                "Even if it is not the life you want or hoped for, it is life - live it.",
                "There is always something to be thankful for.",
                "Small steps every day. \nEvery small step counts.",
                "You might not reach your goal today but that is okay, there is always tomorrow.",
                "Taking a step backwards, after taking a step forwards, \nis not a disaster; it is the cha-cha, your dance of life.",
                "You will always find beauty again, even in the little things.",
                "You can and you will.",
                "Broken crayons still color, \nif you feel broken, do not let that determine your worth, you can still do so much.",
                "You will never be the same again.  \nHow can that be a bad thing.  \nYou will be so much stronger.",
                "We can not fight the wind, but we can adjust our sails.",
                "Storms do not last, then the sun comes out.",
                "You can not cross the ocean merely by standing by the shore.  \nJump in and you will be across before you know it.",
                "20% of something is better than 100% of nothing.",
                "Fear is the enemy, \ncancer is an illness, \nif you talk about it, \ncancer looses the power to scare you.",
                "Toughness is in the soul and spirit, \nnot in muscles.",
                "It is not what is taken away that counts, \nit is what you choose to do with what is left.",
                "Cancer is limited - it CAN NOT cripple love, \nshatter hope, nor can it corrode faith.",
                "Cancer CAN NOT destroy peace, kill friendship, nor can it suppress memories.",
                "Cancer can not silence courage, invade the soul, \nsteal eternal life nor can it conquer the spirit.",
                "Attitude is the little thing that makes a huge difference.",
                "Your potential is greater than any obstacle.",
                "Scars are tattoos with better stories.",
                "I am still standing.",
                "You are still here - breathe.",
                "Let your faith be bigger than your fear.",
                "You can - 'cer' vive.",
                "Strength does not come from physical capacity, it comes from an indomitable will.",
                "Have a good look, this is what a cancer survivor looks like no matter the outside, you are still inside, do not be afraid to come back.",
                "Live large.",
                "I can and I will",
                "Do not wait for the bad things to be over, live your best life - now.",
                "If you can stay strong for your family, you can stay strong for yourself.",
                "You can not just take care of everyone else all the time, \nrelax and let them take care of you.",
                "You can not triumph without the struggle.",
                "Every day is a victory - make it count.",
                "Enjoy the little things because when you look back, they may be the big things.",
                "When you come to the end of your rope, tie a knot and hang on!",
                "What is the point of cancer - that is easy - survive.",
                "You are happy when you choose to be happy, choose wisely.",
                "A life touched by cancer is not a life destroyed by cancer.",
                "Time to live, smile, be happy, sing, dance...",
                "Joy and Sunshine after the rain.",
        };
    }

    @RequiresApi(api = Build.VERSION_CODES.LOLLIPOP)
    String getRandomQuotes(){
        String quote;
        int quotesArrayLen = getQuote().length;
        int randomNum = ThreadLocalRandom.current().nextInt(quotesArrayLen);

        quote = getQuote()[randomNum];
        return quote;
    }
}
